---
- name: Configure Timezone
  timezone:
    name={{ timezone }}

- name: Add APT Repository for Python3.x on xenial
  apt_repository:
    repo: ppa:jonathonf/python-3.6
    state: present

- name: Install Requirement APT Packages
  apt:
    name: '{{ item.name }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - name: build-essential
    - name: libncursesw5-dev
    - name: libgdbm-dev
    - name: libsqlite3-dev
    - name: libbz2-dev
    - name: libffi-dev
    - name: python3-pip
    - name: python3.6
    - name: unzip